### ISSUE TITLE
Example on the wiki

### ISSUE THREAD

**Issue by GaLzZy** [stefvanschie/IF#76] opened 2020-10-15 17:54 UTC
I folowed the emxaple on the wiki so I have this

`public class BankGui {
    public static Gui bankGUI;

    public BankGui() {
        bankGUI = new Gui(6, "Test Bank GUI");
        OutlinePane pane = new OutlinePane(0, 0, 9, 6);
        ItemStack item = new ItemStack(Material.ICE);
        GuiItem guiItem = new GuiItem(item, e -> e.getWhoClicked().sendMessage(ChatColor.AQUA + "YOU CLICKED ON ICE"));
        pane.addItem(guiItem);
        bankGUI.addPane(pane);
    }

    public void openBankGui(Player p) {
        bankGUI.show(p);
    }
}`

And when I create a new BankGui and then call openBankGui I guess an error saying null...

It also did this with other librairies .. Am I missing something ? Might be me just being dumb but if anyone can help would be appreciated :)

**Comment by stefvanschie** [comment] 2020-10-16 10:31
Could you show the stacktrace you're getting when trying to open the gui?

**Comment by GaLzZy** [comment] 2020-10-16 12:17
> Could you show the stacktrace you're getting when trying to open the gui?

I removed gui librairies and created a basic one... But can it be because im on 1.16.3 ?

**Comment by stefvanschie** [comment] 2020-10-16 18:29
The framework should work on 1.16.3, so that shouldn't be the issue.

**Comment by stefvanschie** [comment] 2020-11-18 11:41
Closing this since it has been a month; please re-open this if the issue is not solved.

**Closed by stefvanschie** 2020-11-18 11:41 UTC
Labels: question
